version: '3'

services:
  api:
    # image: api
    build: ./
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/src
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    #volumes:
    #  - /var/lib/postgresql/data

