name: docker-back

on:
  push:
    branches:
      - "main"

jobs:
  docker-back:
    runs-on: ubuntu-latest # contains Docker + Docker compose
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1 # docker compilation more efficient
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 # tools for docker compilation
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # these are not env variables
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out code
        uses: actions/checkout@v2 # pull the code
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: soufcode/2209-wns-hopper-raskolnicode-back:latest